name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
template: |
  ## How to install
  [Pypi - a9s $RESOLVED_VERSION](https://pypi.org/project/a9s/$RESOLVED_VERSION)
  ```bash
  pip install "a9s==$RESOLVED_VERSION"
  ```

  or:
  ```bash
  docker run -v ~/.aws/:/root/.aws -it --rm ghcr.io/iamshobe/a9s:$RESOLVED_VERSION
  ```

  ## Changes

  $CHANGES
