services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,route53,dynamodb,iam,sts,secretsmanager,lambda,ecs,logs,ec2,elbv2,sqs,cloudformation,sns,ssm,ecr,stepfunctions
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
