

name: Bundler

on:
  push:
    tags:
      - 'v*'


jobs:
  bundler:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: 1.1.4
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
        shell: bash
      - shell: bash
        run: |
          python -m poetry version ${{ steps.get_version.outputs.VERSION }}
          echo 'version = "${{ steps.get_version.outputs.VERSION }}"' > a9s/version_file.py
      - shell: bash
        run: poetry install

      - shell: bash
        run: poetry run pyinstaller a9s.spec
      - name: Archive Release
        shell: bash
        run: tar czf 'a9s-${{ steps.get_version.outputs.VERSION }}-${{ matrix.os }}.tar.gz' --directory dist a9s
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'a9s-${{ steps.get_version.outputs.VERSION }}-${{ matrix.os }}.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
